// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name torCalcApp.controller:AboutCtrl
    * @description
    * # AboutCtrl
    * Controller of the torCalcApp
   */
  angular.module('torCalcApp').controller('AboutCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);
