// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name torCalcApp.controller:MainCtrl
    * @description
    * # MainCtrl
    * Controller of the torCalcApp
   */
  angular.module('torCalcApp').controller('MainCtrl', function($scope, $location) {
    var url;
    $scope.search = function(url) {
      var relayBurst, relayRate, urlPath;
      if (url == null) {
        url = true;
      }
      relayRate = Math.round(((parseInt($scope.bw) * 1000000) / 2628000) / 2);
      relayBurst = Math.round(relayRate + relayRate * .75);
      $scope.result = {
        'bw': $scope.bw,
        'acctMax': $scope.bw + ' GB',
        'acctStart': 'month 1 00:00',
        'relayRate': relayRate + ' KBytes',
        'relayBurst': relayBurst + ' KBytes'
      };
      if (url === true) {
        urlPath = '/?bw=' + $scope.bw;
        return history.pushState(null, "", urlPath);
      }
    };
    $scope.typeToggle = function(type, url) {
      var urlPath;
      if (url == null) {
        url = true;
      }
      if (type === 'relay') {
        $scope.relay = true;
        $scope.exit = false;
      }
      if (type === 'exit') {
        $scope.relay = false;
        $scope.exit = true;
      }
      if (url === true) {
        urlPath = '/?bw=' + $scope.bw + '&type=' + type;
        return history.pushState(null, "", urlPath);
      }
    };
    if ($location.search().bw) {
      $scope.bw = $location.search().bw;
      $scope.search(url = false);
    }
    if ($location.search().type && $location.search().bw) {
      return $scope.typeToggle($location.search().type, url = false);
    }
  }).directive('selectOnClick', function($window) {
    return {
      link: function(scope, element) {
        return element.on('click', function() {
          var range, selection;
          selection = $window.getSelection();
          range = document.createRange();
          range.selectNodeContents(element[0]);
          selection.removeAllRanges();
          return selection.addRange(range);
        });
      }
    };
  });

}).call(this);
