// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';

  /**
    * @ngdoc overview
    * @name torCalcApp
    * @description
    * # torCalcApp
    *
    * Main module of the application.
   */
  angular.module('torCalcApp', ['ngAnimate', 'ngCookies', 'ngResource', 'ngRoute', 'ngSanitize']).config(function($routeProvider, $locationProvider) {
    $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).when('/about', {
      templateUrl: 'views/about.html',
      controller: 'AboutCtrl'
    }).otherwise({
      redirectTo: '/'
    });
    return $locationProvider.html5Mode(true);
  });

}).call(this);
